trigger:
- main

pool:
  name: default

stages:
  - stage: Build
    displayName: 'Build'
    jobs:
      - job: BuildJob
        displayName: 'Build Job'
        condition: eq(variables['Build.Reason'], 'PullRequest')
        steps:
          - script: echo "This step runs only for pull requests"
      - job: testJob
        displayName: 'TEST JOB'
        steps:
          - script: echo "THIS IS TEST JOB"
