trigger:
  branches:
    include:
    - main

pr:
- main

pool:
  name: default

stages:
  - stage: terraformInt
    displayName: 'terraform init'
    jobs:
      - job: terraform_init
        displayName: 'terraform init'
        condition: always()
        steps:
          - script: |
              terraform init
          - task: CopyFiles@2
            inputs:
              sourceFolder: $(Build.SourcesDirectory)
              targetFolder: $(Build.ArtifactStagingDirectory)  
          - task: PublishBuildArtifacts@1
            inputs:
              PathtoPublish: '$(Build.ArtifactStagingDirectory)'
              ArtifactName: 'drop'

  - stage: terraformValidatePR
    displayName: 'PR terraform validate'
    jobs:
      - job: terraform_validate
        condition: eq(variables['Build.Reason'], 'PullRequest')
        steps:
        - task: DownloadBuildArtifacts@1
          inputs:
            buildType: 'current'
            downloadType: 'single'
            artifactName: 'drop'
            downloadPath: '$(System.ArtifactsDirectory)'

        - script: |
            cd '$(System.ArtifactsDirectory)'/drop
            echo "Below is the current path"
            pwd
            echo "Setting execution mode"
            chmod -R +x .terraform
            terraform validate


  - stage: terraformPlanPR
    displayName: 'PR terraform plan'
    jobs:
      - job: terraform_plan
        condition: eq(variables['Build.Reason'], 'PullRequest')
        steps:
        - task: DownloadBuildArtifacts@1
          inputs:
            buildType: 'current'
            downloadType: 'single'
            artifactName: 'drop'
            downloadPath: '$(System.ArtifactsDirectory)'

        - script: |
            cd '$(System.ArtifactsDirectory)'/drop
            echo "Below is the current path"
            pwd
            echo "Setting execution mode"
            chmod -R +x .terraform
            terraform plan


  - stage: MergeRequest
    displayName: 'Merge terrafoorm apply'
    jobs:
      - job: terraform_apply
        displayName: 'terraform apply'
        condition: eq(variables['Build.SourceBranch'], 'refs/heads/main')
        steps:
        - task: DownloadBuildArtifacts@1
          inputs:
            buildType: 'current'
            downloadType: 'single'
            artifactName: 'drop'
            downloadPath: '$(System.ArtifactsDirectory)'

        - script: |
            cd '$(System.ArtifactsDirectory)'/drop
            echo "Below is the current path"
            pwd
            echo "Setting execution mode"
            chmod -R +x .terraform
            terraform destroy -auto-approve

      
