trigger:
- main

pool:
  name: default

stages:
  - stage: terraformInt
    displayName: 'terraform init'
    jobs:
      - job: terraform_init
        displayName: 'terraform init'
        condition: eq(variables['Build.Reason'], 'PullRequest')
        steps:
          - script: |
              terraform init

  - stage: terraformValidate
    displayName: 'terraform validate'
    jobs:
      - job: terraform_validate
        displayName: 'terraform validate'
        condition: eq(variables['Build.Reason'], 'PullRequest')
        steps:
          - script: |
              terraform validate

  - stage: terraformPlan
    displayName: 'terraform plan'
    jobs:
      - job: terraform_plan
        displayName: 'terraform plan'
        condition: eq(variables['Build.Reason'], 'PullRequest')
        steps:
          - script: |
              terraform plan

  - stage: MergeRequest
    displayName: 'Merge Request'
    jobs:
      - job: terraform_apply
        displayName: 'terraform apply'
        steps:
          - script: echo "This step runs only when merging into main branch"
          - script: |
              terraform init
              terraform apply -auto-approve
          
      # - job: testJob
      #   displayName: 'TEST JOB'
      #   steps:
      #     - script: |
      #         terraform apply -auto-approve
