trigger:
- main

pool:
  name: default

stages:
  - stage: terraformIntPR
    displayName: 'PR terraform init'
    jobs:
      - job: terraform_init
        displayName: 'terraform init'
        condition: eq(variables['Build.Reason'], 'PullRequest')
        steps:
          - script: |
              terraform init

  - stage: terraformValidatePR
    displayName: 'PR terraform validate'
    jobs:
      - job: terraform_validate
        displayName: 'terraform validate'
        condition: eq(variables['Build.Reason'], 'PullRequest')
        steps:
          - script: |
              terraform validate


  - stage: terraformPlanPR
    displayName: 'PR terraform plan'
    jobs:
      - job: terraform_plan
        condition: eq(variables['Build.Reason'], 'PullRequest')
        steps:
        - task: DownloadBuildArtifacts@1
          inputs:
            buildType: 'current'
            downloadType: 'single'
            artifactName: 'drop'
            downloadPath: '$(System.ArtifactsDirectory)'

        - script: |
            cd '$(System.ArtifactsDirectory)'/drop
            echo "Below is the current path"
            pwd
            echo "Setting execution mode"
            chmod -R +x .terraform
            terraform plan

  - stage: terraformIntPush
    displayName: 'Merge terraform init'
    jobs:
      - job: terraform_init
        displayName: 'Merge Request -> terraform init'
        steps:
          - script: |
              terraform init
          - task: CopyFiles@2
            inputs:
              sourceFolder: $(Build.SourcesDirectory)
              targetFolder: $(Build.ArtifactStagingDirectory)  
          - task: PublishBuildArtifacts@1
            inputs:
              PathtoPublish: '$(Build.ArtifactStagingDirectory)'
              ArtifactName: 'drop'
              #publishLocation: 'Container'

  - stage: MergeRequest
    displayName: 'Merge terrafoorm apply'
    jobs:
      - job: terraform_apply
        displayName: 'terraform apply'
        steps:
        - task: DownloadBuildArtifacts@1
          inputs:
            buildType: 'current'
            downloadType: 'single'
            artifactName: 'drop'
            downloadPath: '$(System.ArtifactsDirectory)'

        - script: |
            cd '$(System.ArtifactsDirectory)'/drop
            echo "Below is the current path"
            pwd
            echo "Setting execution mode"
            chmod -R +x .terraform
            terraform destroy -auto-approve
          
      # - job: testJob
      #   displayName: 'TEST JOB'
      #   steps:
      #     - script: |
      #         terraform apply -auto-approve
      
